on:
  - push

jobs:
  latex_build:
    runs-on: ubuntu-latest
    name: Compiles the project to a pdf
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compile
        uses: ./.github/actions/latex/
        id: latex
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: Thesis
          path: output/thesis.pdf
