on:
  - push

jobs:
  latex_build:
    runs-on: ubuntu-latest
    name: Compiles the project to a pdf
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compile
        uses: ./.github/actions/latex/
        id: latex
